### PR TITLE
Fail early if argc <= 0 or argv[0] is NULL

### PR DESCRIPTION
**Pull request by EliteTK**
Under musl optind will be 1 if getopt is called with argc == 0.
Under glibc it is not quite clear what will happen and I haven't tested
it.

In either case, this triggers a bug where argv ends up pointing at
envp and argc is set to -1 which has further unclear implications on the
execution of the program.

By failing early, these issues can be safely avoided.

fputs and exit are used instead of errx as errx does not have the
information necessary to print a meaningful program name.

### CODE REVIEW

**Comment by ericonr** [comment]
> fputs and exit are used instead of errx as errx does not have the information necessary to print a meaningful program name.

It calls `setprogname` before that, though. Is it not enough?

**Comment by EliteTK** [comment]
@ericonr no. setprogname is handled by libopenbsd and err* are all provided by libc (as bsd extensions). (I first tested this patch with errx and it definitely didn't work which is why I changed to using fputs.)

**Comment by Duncaen** [comment]
Thanks, merged this into a new branch for the last release and tagged a release https://github.com/Duncaen/OpenDoas/releases/tag/v6.8.2.

**Comment by EliteTK** [comment]
I'm closing this since it has been merged in a way which github doesn't appear to understand.

**Pull request closed without merging**
